title: Studentkjellernes personalforening
name: Studentkjellernes personalforening
description: Samarbeidsforening for studentkjellerne ved Universitetet i Oslo. Betalt personell ved medlemsforeningene v√•re er ansatt hos oss.
locale: 'nb-NO'
timezone: Europe/Oslo
url: 'https://spf.no'

# Social sites
social:
  type: Organization
  links:
    - 'https://www.linkedin.com/company/studentkjellernes-personalforening/'

author:
  github: SPF-UiO

# Set up Google Analytics
analytics:
  provider: 'google-gtag'
  google:
    tracking_id: 'UA-4482117-3'


# See Gemfile for source
theme: minimal-mistakes-jekyll

# What should we include and exclude?
include:
  - _pages
  - _redirects

defaults:
  # _pages (our pages)
  - scope:
      path: '_pages'
      type: pages
    values:
      layout: 'single'


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# we don't have any like these
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

